### ISSUE TITLE
Error converting value "Fog"

### ISSUE THREAD

**Issue by CozyMilkTea** [angelobreuer/OpenWeatherMap4NET#2]
need add this to fix the error im getting
Error converting value "Fog" to type 'OpenWeatherMap.Entities.WeatherConditionType'. Path 'weather[0].main', line 1, position 69.

**Comment by angelobreuer** [comment]
Hello @CozyMilkTea,
thanks for your bug report!

I've added the new weather condition types listed in the API documentation (see: https://openweathermap.org/weather-conditions).
