### ISSUE TITLE
WindInformation.Direction

### ISSUE THREAD

**Issue by bosko19** [angelobreuer/OpenWeatherMap4NET#5]
The WindInformation.Direction ("deg") property has a JsonRequired attribute.

Ran into an issue today where the "deg" property was not returned by the OpenWeather API, throwing an exception. 

Removing the JsonRequired attribute resolved the problem.

**Comment by angelobreuer** [comment]
Hello @bosko19,
thanks for your report!

I fixed the issue and will publish the release now (1.0.5).
